# Generated by Django 3.2.10 on 2021-12-30 23:09

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
                ('name_cs', models.CharField(max_length=127, null=True, unique=True)),
                ('name_en', models.CharField(max_length=127, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=63)),
                ('name_cs', models.CharField(max_length=63, null=True)),
                ('name_en', models.CharField(max_length=63, null=True)),
                ('city', models.CharField(blank=True, max_length=127, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('street_number', models.CharField(blank=True, max_length=63, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=63, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True, verbose_name='Latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True, verbose_name='Longitude')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='fantasion_locations.country')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
