# Generated by Django 3.2.11 on 2022-01-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=127, unique=True, verbose_name='Country name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_cs',
            field=models.CharField(max_length=127, null=True, unique=True, verbose_name='Country name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=127, null=True, unique=True, verbose_name='Country name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='fantasion_locations.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=63, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name_cs',
            field=models.CharField(max_length=63, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='location',
            name='street_number',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Street number'),
        ),
    ]
