# Generated by Django 3.2.11 on 2022-01-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_locations', '0002_auto_20220116_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='fuzzy_name',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Fuzzy name'),
        ),
        migrations.AddField(
            model_name='location',
            name='fuzzy_name_cs',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Fuzzy name'),
        ),
        migrations.AddField(
            model_name='location',
            name='fuzzy_name_en',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Fuzzy name'),
        ),
    ]
