# Generated by Django 3.2.12 on 2022-04-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_locations', '0003_auto_20220123_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='CZ', max_length=3, unique=True, verbose_name='Country code'),
            preserve_default=False,
        ),
    ]
