# Generated by Django 3.2.10 on 2022-01-09 02:52

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortPromotionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('text', models.TextField(help_text='Write down a short quote displayed on the web for fun and topromote the atmosphere on the summer camp', verbose_name='Short Promotion Text')),
                ('text_cs', models.TextField(help_text='Write down a short quote displayed on the web for fun and topromote the atmosphere on the summer camp', null=True, verbose_name='Short Promotion Text')),
                ('text_en', models.TextField(help_text='Write down a short quote displayed on the web for fun and topromote the atmosphere on the summer camp', null=True, verbose_name='Short Promotion Text')),
                ('quote_owner', models.CharField(help_text='A name that will be displayed as the original author of the quote', max_length=63, verbose_name='Quote Owner')),
                ('quote_owner_cs', models.CharField(help_text='A name that will be displayed as the original author of the quote', max_length=63, null=True, verbose_name='Quote Owner')),
                ('quote_owner_en', models.CharField(help_text='A name that will be displayed as the original author of the quote', max_length=63, null=True, verbose_name='Quote Owner')),
            ],
            options={
                'verbose_name': 'Short Promotion Text',
                'verbose_name_plural': 'Short Promotion Texts',
            },
        ),
    ]
