# Generated by Django 3.2.11 on 2022-01-18 18:16

from django.db import migrations, models
import django_extensions.db.fields
import fantasion_generics.models
import fantasion_generics.titles


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, verbose_name='Title')),
                ('title_cs', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True, verbose_name='Title')),
                ('title_en', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True, verbose_name='Title')),
                ('description', fantasion_generics.titles.DescriptionField(help_text='Object description', verbose_name='Description')),
                ('description_cs', fantasion_generics.titles.DescriptionField(help_text='Object description', null=True, verbose_name='Description')),
                ('description_en', fantasion_generics.titles.DescriptionField(help_text='Object description', null=True, verbose_name='Description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('title',))),
                ('slug_cs', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=('title',))),
                ('slug_en', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=('title',))),
                ('key', models.CharField(help_text='Unique key used to reference the article directly on the API', max_length=32, unique=True, verbose_name='Article key')),
                ('public', fantasion_generics.models.VisibilityField(default=True, help_text='Public objects will be visible on the website', verbose_name='Public')),
            ],
            options={
                'verbose_name': 'Static Articles',
                'verbose_name_plural': 'Static Articles',
            },
        ),
    ]
