# Generated by Django 3.2.11 on 2022-01-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_content', '0002_staticarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticarticle',
            name='text',
            field=models.TextField(default=None, help_text='Your article content formatted in Markdown', verbose_name='Article text'),
            preserve_default=False,
        ),
    ]
