# Generated by Django 3.2.11 on 2022-01-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_content', '0003_staticarticle_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticarticle',
            name='text_cs',
            field=models.TextField(help_text='Your article content formatted in Markdown', null=True, verbose_name='Article text'),
        ),
        migrations.AddField(
            model_name='staticarticle',
            name='text_en',
            field=models.TextField(help_text='Your article content formatted in Markdown', null=True, verbose_name='Article text'),
        ),
    ]
