# Generated by Django 3.2.11 on 2022-01-18 21:09

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import fantasion_generics.media
import fantasion_generics.titles
import fantasion_generics.upload_path
import fantasion_generics.videos
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_content', '0004_auto_20220118_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticArticleMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('height', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Height')),
                ('width', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Width')),
                ('local_photo', versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Image file', width_field='width')),
                ('local_video', fantasion_generics.videos.VideoField(blank=True, duration_field='duration', height_field='height', max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Video file', width_field='width')),
                ('duration', models.PositiveBigIntegerField(blank=True, null=True)),
                ('title', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True, verbose_name='Title')),
                ('title_cs', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True, verbose_name='Title')),
                ('title_en', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True, verbose_name='Title')),
                ('description', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True, verbose_name='Description')),
                ('description_cs', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True, verbose_name='Description')),
                ('description_en', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True, verbose_name='Description')),
                ('parent', fantasion_generics.media.MediaParentField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='fantasion_content.staticarticle', verbose_name='Parent object')),
            ],
            options={
                'verbose_name': 'Media Object',
                'verbose_name_plural': 'Media Objects',
                'abstract': False,
            },
        ),
    ]
