# Generated by Django 3.2.11 on 2022-01-20 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_content', '0005_staticarticlemedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticarticlemedia',
            name='created',
        ),
        migrations.RemoveField(
            model_name='staticarticlemedia',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='staticarticlemedia',
            name='title',
        ),
        migrations.RemoveField(
            model_name='staticarticlemedia',
            name='title_cs',
        ),
        migrations.RemoveField(
            model_name='staticarticlemedia',
            name='title_en',
        ),
    ]
