# Generated by Django 3.2.11 on 2022-01-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_content', '0006_auto_20220120_2355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortPromotionText',
            new_name='FlavourText',
        ),
    ]
