# Generated by Django 3.2.11 on 2022-01-23 14:48

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import fantasion_generics.media
import fantasion_generics.models
import fantasion_generics.titles
import fantasion_generics.upload_path
import fantasion_generics.videos
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_content', '0009_auto_20220122_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('question', models.TextField(help_text='Write the question from perspective of the person asking it.', verbose_name='Question')),
                ('question_cs', models.TextField(help_text='Write the question from perspective of the person asking it.', null=True, verbose_name='Question')),
                ('question_en', models.TextField(help_text='Write the question from perspective of the person asking it.', null=True, verbose_name='Question')),
                ('answer', models.TextField(help_text='Write the best positive answer that resolves all issues of the questioner and gives hope for the future.', verbose_name='Answer')),
                ('answer_cs', models.TextField(help_text='Write the best positive answer that resolves all issues of the questioner and gives hope for the future.', null=True, verbose_name='Answer')),
                ('answer_en', models.TextField(help_text='Write the best positive answer that resolves all issues of the questioner and gives hope for the future.', null=True, verbose_name='Answer')),
                ('importance', fantasion_generics.models.ImportanceField(default=0, help_text='More important objects will appear on the top or sooner on the page', verbose_name='Object Importance')),
                ('public', fantasion_generics.models.VisibilityField(default=True, help_text='Public objects will be visible on the website', verbose_name='Public')),
            ],
            options={
                'verbose_name': 'Frequently Asked Question',
                'verbose_name_plural': 'Frequently Asked Questions',
                'ordering': ['-importance'],
            },
        ),
        migrations.CreateModel(
            name='FrequentlyAskedQuestionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Height')),
                ('width', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Width')),
                ('local_photo', versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Image file', width_field='width')),
                ('local_video', fantasion_generics.videos.VideoField(blank=True, duration_field='duration', height_field='height', max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Video file', width_field='width')),
                ('duration', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True, verbose_name='Description')),
                ('description_cs', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True, verbose_name='Description')),
                ('description_en', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True, verbose_name='Description')),
                ('parent', fantasion_generics.media.MediaParentField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='fantasion_content.frequentlyaskedquestion', verbose_name='Parent object')),
            ],
            options={
                'verbose_name': 'Media Object',
                'verbose_name_plural': 'Media Objects',
                'abstract': False,
            },
        ),
    ]
