# Generated by Django 3.2.11 on 2022-01-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_content', '0011_auto_20220123_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='detailed_answer',
            field=models.TextField(blank=True, help_text='Write all the details, do not spare the letters', null=True, verbose_name='Detailed Answer'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='detailed_answer_cs',
            field=models.TextField(blank=True, help_text='Write all the details, do not spare the letters', null=True, verbose_name='Detailed Answer'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='detailed_answer_en',
            field=models.TextField(blank=True, help_text='Write all the details, do not spare the letters', null=True, verbose_name='Detailed Answer'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='short_answer',
            field=models.TextField(help_text='Write a quick summarizing positive answer that resolves the question', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='short_answer_cs',
            field=models.TextField(help_text='Write a quick summarizing positive answer that resolves the question', null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='short_answer_en',
            field=models.TextField(help_text='Write a quick summarizing positive answer that resolves the question', null=True, verbose_name='Answer'),
        ),
    ]
