# Generated by Django 3.2.11 on 2022-01-31 21:29

from django.db import migrations
import fantasion_generics.titles


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_content', '0012_auto_20220123_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskedquestionmedia',
            name='description',
            field=fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestionmedia',
            name='description_cs',
            field=fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestionmedia',
            name='description_en',
            field=fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='staticarticle',
            name='description',
            field=fantasion_generics.titles.DescriptionField(help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='staticarticle',
            name='description_cs',
            field=fantasion_generics.titles.DescriptionField(help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='staticarticle',
            name='description_en',
            field=fantasion_generics.titles.DescriptionField(help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='staticarticlemedia',
            name='description',
            field=fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='staticarticlemedia',
            name='description_cs',
            field=fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='staticarticlemedia',
            name='description_en',
            field=fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
    ]
