# Generated by Django 3.2.11 on 2022-02-01 17:52

from django.db import migrations
import fantasion_generics.photos
import fantasion_generics.upload_path


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_content', '0013_auto_20220131_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskedquestionmedia',
            name='local_photo',
            field=fantasion_generics.photos.LocalPhotoField(blank=True, height_field='height', max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Image file', width_field='width'),
        ),
        migrations.AlterField(
            model_name='staticarticlemedia',
            name='local_photo',
            field=fantasion_generics.photos.LocalPhotoField(blank=True, height_field='height', max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Image file', width_field='width'),
        ),
    ]
