# Generated by Django 3.2.11 on 2022-02-05 14:14

from django.db import migrations
import fantasion_generics.models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_content', '0014_auto_20220201_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='detailed_answer',
            field=fantasion_generics.models.MarkdownField(blank=True, help_text='Write all the details, do not spare the letters', null=True, verbose_name='Detailed Answer'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='detailed_answer_cs',
            field=fantasion_generics.models.MarkdownField(blank=True, help_text='Write all the details, do not spare the letters', null=True, verbose_name='Detailed Answer'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='detailed_answer_en',
            field=fantasion_generics.models.MarkdownField(blank=True, help_text='Write all the details, do not spare the letters', null=True, verbose_name='Detailed Answer'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='short_answer',
            field=fantasion_generics.models.MarkdownField(help_text='Write a quick summarizing positive answer that resolves the question', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='short_answer_cs',
            field=fantasion_generics.models.MarkdownField(help_text='Write a quick summarizing positive answer that resolves the question', null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='short_answer_en',
            field=fantasion_generics.models.MarkdownField(help_text='Write a quick summarizing positive answer that resolves the question', null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='staticarticle',
            name='text',
            field=fantasion_generics.models.MarkdownField(help_text='Your article content formatted in Markdown', verbose_name='Article text'),
        ),
        migrations.AlterField(
            model_name='staticarticle',
            name='text_cs',
            field=fantasion_generics.models.MarkdownField(help_text='Your article content formatted in Markdown', null=True, verbose_name='Article text'),
        ),
        migrations.AlterField(
            model_name='staticarticle',
            name='text_en',
            field=fantasion_generics.models.MarkdownField(help_text='Your article content formatted in Markdown', null=True, verbose_name='Article text'),
        ),
    ]
