# Generated by Django 3.2.11 on 2022-02-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_content', '0015_auto_20220205_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticarticle',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='staticarticle',
            name='slug_cs',
        ),
        migrations.RemoveField(
            model_name='staticarticle',
            name='slug_en',
        ),
    ]
