# Generated by Django 3.2.11 on 2022-02-21 00:55

from django.db import migrations, models
import fantasion_generics.models
import fantasion_generics.titles


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_content', '0017_monster_monstermedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='description_cs',
            field=fantasion_generics.titles.DescriptionField(help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='monster',
            name='description_en',
            field=fantasion_generics.titles.DescriptionField(help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='monster',
            name='species_cs',
            field=models.CharField(help_text='Name of the monsters species.', max_length=255, null=True, verbose_name='Species'),
        ),
        migrations.AddField(
            model_name='monster',
            name='species_en',
            field=models.CharField(help_text='Name of the monsters species.', max_length=255, null=True, verbose_name='Species'),
        ),
        migrations.AddField(
            model_name='monster',
            name='text_cs',
            field=fantasion_generics.models.MarkdownField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='monster',
            name='text_en',
            field=fantasion_generics.models.MarkdownField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='monstermedia',
            name='description_cs',
            field=fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='monstermedia',
            name='description_en',
            field=fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
    ]
