# Generated by Django 3.2.12 on 2022-04-02 17:28

from django.db import migrations, models
import fantasion_generics.photos
import fantasion_generics.titles
import fantasion_generics.upload_path


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_content', '0018_auto_20220221_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='avatar',
            field=fantasion_generics.photos.LocalPhotoField(blank=True, max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Image file'),
        ),
        migrations.AddField(
            model_name='monster',
            name='title',
            field=fantasion_generics.titles.TitleField(default='', help_text='Object name', max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='title_cs',
            field=fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='monster',
            name='title_en',
            field=fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='description',
            field=models.CharField(help_text='Short (max 5 words) description of monster.', max_length=30, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='description_cs',
            field=models.CharField(help_text='Short (max 5 words) description of monster.', max_length=30, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='description_en',
            field=models.CharField(help_text='Short (max 5 words) description of monster.', max_length=30, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='species',
            field=models.CharField(help_text='Name of the monster species.', max_length=30, verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='species_cs',
            field=models.CharField(help_text='Name of the monster species.', max_length=30, null=True, verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='species_en',
            field=models.CharField(help_text='Name of the monster species.', max_length=30, null=True, verbose_name='Species'),
        ),
    ]
