# Generated by Django 4.1.5 on 2023-01-21 14:51

from django.db import migrations
import fantasion_generics.models
import fantasion_generics.visibility


class Migration(migrations.Migration):

    dependencies = [
        ("fantasion_content", "0019_auto_20220402_1928"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="frequentlyaskedquestion",
            name="public",
        ),
        migrations.RemoveField(
            model_name="monster",
            name="public",
        ),
        migrations.RemoveField(
            model_name="staticarticle",
            name="public",
        ),
        migrations.AddField(
            model_name="frequentlyaskedquestion",
            name="visibility",
            field=fantasion_generics.visibility.VisibilityField(
                choices=[(1, "🌐 Public"), (2, "🔒 Private"), (3, "🚫 Hidden")],
                default=1,
                help_text="Public objects will be visible on the website",
                verbose_name="Visibility",
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="visibility",
            field=fantasion_generics.visibility.VisibilityField(
                choices=[(1, "🌐 Public"), (2, "🔒 Private"), (3, "🚫 Hidden")],
                default=1,
                help_text="Public objects will be visible on the website",
                verbose_name="Visibility",
            ),
        ),
        migrations.AddField(
            model_name="staticarticle",
            name="visibility",
            field=fantasion_generics.visibility.VisibilityField(
                choices=[(1, "🌐 Public"), (2, "🔒 Private"), (3, "🚫 Hidden")],
                default=1,
                help_text="Public objects will be visible on the website",
                verbose_name="Visibility",
            ),
        ),
        migrations.AlterField(
            model_name="staticarticle",
            name="description",
            field=fantasion_generics.models.DetailedDescriptionField(
                blank=True,
                help_text="Detailed verbose description formatted in Markdown. Thereis no text limit.",
                null=True,
                verbose_name="Detailed Description",
            ),
        ),
        migrations.AlterField(
            model_name="staticarticle",
            name="description_cs",
            field=fantasion_generics.models.DetailedDescriptionField(
                blank=True,
                help_text="Detailed verbose description formatted in Markdown. Thereis no text limit.",
                null=True,
                verbose_name="Detailed Description",
            ),
        ),
        migrations.AlterField(
            model_name="staticarticle",
            name="description_en",
            field=fantasion_generics.models.DetailedDescriptionField(
                blank=True,
                help_text="Detailed verbose description formatted in Markdown. Thereis no text limit.",
                null=True,
                verbose_name="Detailed Description",
            ),
        ),
    ]
