# Generated by Django 3.2.10 on 2021-12-30 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import fantasion_generics.titles
import fantasion_generics.upload_path
import fantasion_generics.videos


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('title_cs', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('title_en', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('description', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
                ('description_cs', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
                ('description_en', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255)),
                ('owner', models.ForeignKey(help_text='Family owner acts as a superadmin.', on_delete=django.db.models.deletion.RESTRICT, related_name='families', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('title_cs', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('title_en', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('description', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
                ('description_cs', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
                ('description_en', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255)),
                ('title_cs', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True)),
                ('title_en', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True)),
                ('description', fantasion_generics.titles.DescriptionField(help_text='Object description')),
                ('description_cs', fantasion_generics.titles.DescriptionField(help_text='Object description', null=True)),
                ('description_en', fantasion_generics.titles.DescriptionField(help_text='Object description', null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('title',))),
                ('slug_cs', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=('title',))),
                ('slug_en', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=('title',))),
                ('public', models.BooleanField(default=False, help_text='Public profiles will be visible on the website')),
                ('owner', models.ForeignKey(blank=True, default=None, help_text='Owner of the profile will be able to edit the profile', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('height', models.PositiveBigIntegerField(blank=True, null=True)),
                ('width', models.PositiveBigIntegerField(blank=True, null=True)),
                ('local_photo', models.ImageField(blank=True, height_field='height', max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Image file', width_field='width')),
                ('local_video', fantasion_generics.videos.VideoField(blank=True, duration_field='duration', height_field='height', max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Video file', width_field='width')),
                ('duration', models.PositiveBigIntegerField(blank=True, null=True)),
                ('title', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('title_cs', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('title_en', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('description', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
                ('description_cs', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
                ('description_en', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='fantasion_people.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('role', models.PositiveIntegerField(choices=[(1, 'Administrator'), (2, 'Legal representative'), (3, 'Spectator')], default=3)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='fantasion_people.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
