# Generated by Django 3.2.11 on 2022-01-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_people', '0002_auto_20220116_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='text',
            field=models.TextField(default=None, help_text='Full text of the profile formatted in Markdown', verbose_name='Profile text'),
            preserve_default=False,
        ),
    ]
