# Generated by Django 3.2.11 on 2022-02-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_people', '0007_auto_20220201_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, help_text='Extremely short description of the relationship between this person and Fantasion, three or four words ideal', max_length=63, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title_cs',
            field=models.CharField(blank=True, help_text='Extremely short description of the relationship between this person and Fantasion, three or four words ideal', max_length=63, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title_en',
            field=models.CharField(blank=True, help_text='Extremely short description of the relationship between this person and Fantasion, three or four words ideal', max_length=63, null=True, verbose_name='Job Title'),
        ),
    ]
