# Generated by Django 3.2.11 on 2022-02-01 15:28

from django.db import migrations
import fantasion_generics.models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_people', '0008_auto_20220201_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='importance',
            field=fantasion_generics.models.ImportanceField(default=0, help_text='More important objects will appear on the top or sooner on the page', verbose_name='Object Importance'),
        ),
    ]
