# Generated by Django 3.2.11 on 2022-02-05 14:14

from django.db import migrations
import fantasion_generics.models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_people', '0010_auto_20220201_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='text',
            field=fantasion_generics.models.MarkdownField(blank=True, help_text='Full text of the profile formatted in Markdown', null=True, verbose_name='Profile text'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='text_cs',
            field=fantasion_generics.models.MarkdownField(blank=True, help_text='Full text of the profile formatted in Markdown', null=True, verbose_name='Profile text'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='text_en',
            field=fantasion_generics.models.MarkdownField(blank=True, help_text='Full text of the profile formatted in Markdown', null=True, verbose_name='Profile text'),
        ),
    ]
