# Generated by Django 3.2.12 on 2022-04-02 17:35

from django.db import migrations, models
import django_extensions.db.fields
import fantasion_generics.titles


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_people', '0012_auto_20220205_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True, verbose_name='Title')),
                ('description', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description')),
            ],
            options={
                'verbose_name': 'Diet',
                'verbose_name_plural': 'Diets',
            },
        ),
    ]
