# Generated by Django 3.2.12 on 2022-04-02 17:37

from django.db import migrations
import fantasion_generics.titles


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_people', '0013_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='description_cs',
            field=fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='diet',
            name='description_en',
            field=fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='diet',
            name='title_cs',
            field=fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='diet',
            name='title_en',
            field=fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
