# Generated by Django 3.2.13 on 2022-04-30 22:59

from django.db import migrations
import fantasion_generics.titles


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_people', '0014_auto_20220402_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='title',
            field=fantasion_generics.titles.TitleField(default=None, help_text='Object name', max_length=255, unique=True, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allergy',
            name='title_cs',
            field=fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='title_en',
            field=fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='title',
            field=fantasion_generics.titles.TitleField(default=None, help_text='Object name', max_length=255, unique=True, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diet',
            name='title_cs',
            field=fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='title_en',
            field=fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='title',
            field=fantasion_generics.titles.TitleField(default=None, help_text='Object name', max_length=255, unique=True, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hobby',
            name='title_cs',
            field=fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='title_en',
            field=fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
    ]
