# Generated by Django 4.1.5 on 2023-01-21 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fantasion_people", "0015_auto_20220501_0059"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Owner of the profile will be able to edit the profile",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="profiles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
    ]
