# Generated by Django 4.1.5 on 2023-01-21 14:51

from django.db import migrations
import fantasion_generics.visibility


class Migration(migrations.Migration):

    dependencies = [
        ("fantasion_people", "0016_alter_profile_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="public",
        ),
        migrations.AddField(
            model_name="profile",
            name="visibility",
            field=fantasion_generics.visibility.VisibilityField(
                choices=[(1, "🌐 Public"), (2, "🔒 Private"), (3, "🚫 Hidden")],
                default=1,
                help_text="Public objects will be visible on the website",
                verbose_name="Visibility",
            ),
        ),
    ]
