# Generated by Django 4.1.10 on 2023-07-30 03:51

from django.db import migrations
import fantasion_generics.visibility


class Migration(migrations.Migration):
    dependencies = [
        ("fantasion_people", "0018_alter_profile_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="visibility",
            field=fantasion_generics.visibility.VisibilityField(
                choices=[(1, "🌏 Public"), (2, "🔒 Private"), (3, "🚫 Hidden")],
                default=1,
                help_text="Public objects will be visible on the website",
                verbose_name="👁 Visibility",
            ),
        ),
    ]
