# Generated by Django 3.2.11 on 2022-02-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion', '0002_auto_20220209_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
