# Generated by Django 3.2.11 on 2022-02-09 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion', '0003_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('email', models.EmailField(help_text='Validated e-mail address', max_length=254, verbose_name='email address')),
                ('secret', models.CharField(help_text='User will see this next to the link', max_length=63, verbose_name='Secret Key')),
                ('expires_on', models.DateTimeField(help_text='User will be able to use this key until this date time.', verbose_name='Expires on')),
                ('next_step', models.PositiveSmallIntegerField(choices=[(1, 'Create password')], verbose_name='Next step')),
                ('sent', models.PositiveIntegerField(default=0, help_text='How many times was this verification sent', verbose_name='Sent times')),
                ('used', models.BooleanField(default=False, help_text='Has this key been used?', verbose_name='Used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
