# Generated by Django 3.2.11 on 2022-02-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion', '0004_emailverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'Email Verification', 'verbose_name_plural': 'Email Verifications'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': ('User',), 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='password_created',
            field=models.BooleanField(default=False, verbose_name='Has password'),
        ),
    ]
