# Generated by Django 3.2.11 on 2022-02-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion', '0005_auto_20220219_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='next_step',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Create password'), (2, 'Restore password')], verbose_name='Next step'),
        ),
    ]
