# Generated by Django 3.2.12 on 2022-04-03 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_locations', '0003_auto_20220123_0335'),
        ('fantasion', '0008_auto_20220402_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('city', models.CharField(blank=True, max_length=127, null=True, verbose_name='City')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street')),
                ('street_number', models.CharField(blank=True, max_length=63, null=True, verbose_name='Street number')),
                ('postal_code', models.CharField(blank=True, max_length=63, null=True, verbose_name='Postal code')),
                ('title', models.CharField(help_text='Human readable identifier that will help user select this address, like "Home"', max_length=32, verbose_name='Title')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to='fantasion_locations.country', verbose_name='Country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
                'unique_together': {('user', 'title')},
            },
        ),
    ]
