# Generated by Django 3.2.12 on 2022-04-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion', '0009_useraddress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraddress',
            unique_together=set(),
        ),
    ]
