# Generated by Django 4.1.5 on 2023-01-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fantasion", "0010_alter_useraddress_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
