from django.utils.translation import ugettext_lazy as _

ACCOUNT_DRIVER_OFFLINE = 1
ACCOUNT_DRIVER_FIO = 2

ACCOUNT_DRIVER_CHOICES = (
    (ACCOUNT_DRIVER_OFFLINE, _('Offline')),
    (ACCOUNT_DRIVER_FIO, _('Fio Banka')),
)

DEBT_SOURCE_MANUAL = 1
DEBT_SOURCE_GENERATED_INITIAL = 2
DEBT_SOURCE_GENERATED_RECURRING = 3
DEBT_SOURCE_GENERATED_ORDER = 4

DEBT_SOURCE_CHOICES = (
    (DEBT_SOURCE_MANUAL, _('Manually created')),
    (DEBT_SOURCE_GENERATED_INITIAL, _('Initial debt')),
    (DEBT_SOURCE_GENERATED_RECURRING, _('Recurring generated')),
    (DEBT_SOURCE_GENERATED_ORDER, _('Created from order')),
)

DEBT_TYPE_DEPOSIT = 1
DEBT_TYPE_SURCHARGE = 2
DEBT_TYPE_FULL_PAYMENT = 3

DEBT_TYPE_CHOICES = (
    (DEBT_TYPE_DEPOSIT, _('Deposit')),
    (DEBT_TYPE_SURCHARGE, _('Surcharge')),
    (DEBT_TYPE_FULL_PAYMENT, _('Full Payment')),
)

PROMISE_STATUS_EXPECTED = 1
PROMISE_STATUS_DEPOSIT_PAID = 5
PROMISE_STATUS_PAID = 2
PROMISE_STATUS_OVERPAID = 4
PROMISE_STATUS_UNDERPAID = 3

PROMISE_STATUS_CHOICES = (
    (PROMISE_STATUS_EXPECTED, _('Expected')),
    (PROMISE_STATUS_DEPOSIT_PAID, _('Deposit Paid')),
    (PROMISE_STATUS_PAID, _('Paid')),
    (PROMISE_STATUS_UNDERPAID, _('Underpaid')),
    (PROMISE_STATUS_OVERPAID, _('Overpaid')),
)

PROMISE_WAS_PAID = (PROMISE_STATUS_PAID, PROMISE_STATUS_OVERPAID)

RECURRENCE_NONE = None
RECURRENCE_MONTHLY = 'P1M'
RECURRENCE_YEARLY = 'P1Y'

RECURRENCE_CHOICES = (
    (RECURRENCE_NONE, _('Never')),
    (RECURRENCE_MONTHLY, _('Monthly')),
    (RECURRENCE_YEARLY, _('Yearly')),
)

SCRAPE_SOURCE_MANUAL = 1
SCRAPE_SOURCE_CRON = 2

SCRAPE_SOURCE_CHOICES = (
    (SCRAPE_SOURCE_MANUAL, _('Manual')),
    (SCRAPE_SOURCE_CRON, _('Cron')),
)

SCRAPE_STATUS_REQUEST = 1
SCRAPE_STATUS_SUCCESS = 2
SCRAPE_STATUS_FAILURE = 3

SCRAPE_STATUS_CHOICES = (
    (SCRAPE_STATUS_REQUEST, _('Requested')),
    (SCRAPE_STATUS_SUCCESS, _('Succeeded')),
    (SCRAPE_STATUS_FAILURE, _('Failed')),
)
