from django.utils.translation import ugettext_lazy as _

ACCOUNT_DRIVER_OFFLINE = 1
ACCOUNT_DRIVER_CSOB = 2

ACCOUNT_DRIVER_CHOICES = (
    (ACCOUNT_DRIVER_OFFLINE, _('Offline')),
    (ACCOUNT_DRIVER_CSOB, _('ČSOB')),
)

DEBT_SOURCE_MANUAL = 1
DEBT_SOURCE_GENERATED_INITIAL = 2
DEBT_SOURCE_GENERATED_RECURRING = 3

DEBT_SOURCE_CHOICES = (
    (DEBT_SOURCE_MANUAL, _('Manually created')),
    (DEBT_SOURCE_GENERATED_INITIAL, _('Initial debt')),
    (DEBT_SOURCE_GENERATED_RECURRING, _('Recurring generated')),
)

PROMISE_STATUS_EXPECTED = 1
PROMISE_STATUS_PAID = 2
PROMISE_STATUS_UNDERPAID = 3
PROMISE_STATUS_OVERPAID = 4

PROMISE_STATUS_CHOICES = (
    (PROMISE_STATUS_EXPECTED, _('Expected')),
    (PROMISE_STATUS_PAID, _('Paid')),
    (PROMISE_STATUS_UNDERPAID, _('Underpaid')),
    (PROMISE_STATUS_OVERPAID, _('Overpaid')),
)

RECURRENCE_NONE = None
RECURRENCE_MONTHLY = 'P1M'
RECURRENCE_YEARLY = 'P1Y'

RECURRENCE_CHOICES = (
    (RECURRENCE_NONE, _('Never')),
    (RECURRENCE_MONTHLY, _('Monthly')),
    (RECURRENCE_YEARLY, _('Yearly')),
)

SCRAPE_SOURCE_MANUAL = 1
SCRAPE_SOURCE_CRON = 2

SCRAPE_SOURCE_CHOICES = (
    (SCRAPE_SOURCE_MANUAL, _('Manual')),
    (SCRAPE_SOURCE_CRON, _('Cron')),
)

SCRAPE_STATUS_REQUEST = 1
SCRAPE_STATUS_SUCCESS = 2
SCRAPE_STATUS_FAILURE = 3

SCRAPE_STATUS_CHOICES = (
    (SCRAPE_STATUS_REQUEST, _('Requested')),
    (SCRAPE_STATUS_SUCCESS, _('Succeeded')),
    (SCRAPE_STATUS_FAILURE, _('Failed')),
)
