[tool.poetry]
name = "fantasion-backend"
version = "0.1.0"
description = "Backend for Fantasion website"
authors = ["Pavel Žák <pavel@zak.global>"]
packages = [
  { include = "fantasion" },
  { include = "fantasion_api" },
  { include = "fantasion_banking" },
  { include = "fantasion_content" },
  { include = "fantasion_domain" },
  { include = "fantasion_eshop" },
  { include = "fantasion_expeditions" },
  { include = "fantasion_generics" },
  { include = "fantasion_locations" },
  { include = "fantasion_people" },
  { include = "fantasion_signups" },
]
include = [
  "manage.py",
  "**/*.mo",
]

[tool.poetry.dependencies]
czech-sort = "1.1.0"
django-admin-sso = "5.1.0"
django-cors-headers = "3.13.0"
django-encrypted-model-fields = "0.6.5"
django-extensions = "3.2.3"
django-filter = "22.1"
django-modeltranslation = "0.18.11"
django-money = "3.0.0"
django-nested-admin = "4.0.2"
django-phonenumber-field = {version = "7.0.2", extras = ["phonenumbers"]}
djangorestframework-camel-case = "1.3.0"
djangorestframework = "3.14.0"
django-simplemde = "0.1.4"
django-storages = {version = "1.13.2", extras = ["google"]}
django-versatileimagefield = "2.2"
django = "4.1.10"
ffmpeg = "^1.4"
fiobank = "3.0.0"
gunicorn = "20.1.0"
markdown = "3.3.6"
pillow = "9.4.0"
psycopg2-binary = "2.9.5"
python-dateutil = "2.8.2"
python-magic-bin = {version = "0.4.14", platform = "win32"}
python = "^3.10"
qrcode = "^7.4.2"
djangomni-search = "0.3.0"

[tool.poetry.group.dev.dependencies]
flake8 = "6.0.0"
freezegun = "1.2.2"
model-bakery = "1.9.0"
pytest = "7.2"
yapf = "0.32.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
