# Generated by Django 3.2.12 on 2022-04-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='constant_symbol',
            field=models.BigIntegerField(blank=True, help_text='Purpose code of the payment specified by Czech banking system.', null=True, verbose_name='Constant Symbol'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='variable_symbol',
            field=models.BigIntegerField(blank=True, help_text='Optional payment identifier', null=True, verbose_name='Variable Symbol'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='constant_symbol',
            field=models.BigIntegerField(blank=True, help_text='Purpose code of the payment specified by Czech banking system.', null=True, verbose_name='Constant Symbol'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='variable_symbol',
            field=models.BigIntegerField(blank=True, help_text='Optional payment identifier', null=True, verbose_name='Variable Symbol'),
        ),
    ]
