# Generated by Django 3.2.12 on 2022-04-02 22:54

from django.db import migrations
import fantasion_generics.titles


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_banking', '0002_auto_20220403_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description_cs',
            field=fantasion_generics.titles.DescriptionField(help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='account',
            name='description_en',
            field=fantasion_generics.titles.DescriptionField(help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='account',
            name='title_cs',
            field=fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='account',
            name='title_en',
            field=fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='description_cs',
            field=fantasion_generics.titles.DescriptionField(help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='description_en',
            field=fantasion_generics.titles.DescriptionField(help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='title_cs',
            field=fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='title_en',
            field=fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='debt',
            name='description_cs',
            field=fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='debt',
            name='description_en',
            field=fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description'),
        ),
    ]
