# Generated by Django 3.2.12 on 2022-04-03 11:08

from decimal import Decimal
from django.db import migrations
import fantasion_generics.money


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_banking', '0003_auto_20220403_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ballance',
            field=fantasion_generics.money.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='CZK', max_digits=14, verbose_name='Ballance'),
        ),
    ]
