# Generated by Django 3.2.12 on 2022-04-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_banking', '0004_alter_account_ballance'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='debt_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Deposit'), (2, 'Surcharge')], default=None, null=True),
        ),
    ]
