# Generated by Django 3.2.12 on 2022-04-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_banking', '0006_auto_20220407_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='driver',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Offline'), (2, 'Fio Banka')], null=True, verbose_name='Driver'),
        ),
    ]
