# Generated by Django 3.2.10 on 2021-12-30 23:09

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import fantasion_generics.titles
import fantasion_generics.upload_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fantasion_people', '0001_initial'),
        ('fantasion_expeditions', '0001_initial'),
        ('fantasion_eshop', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fantasion_eshop.orderitem')),
                ('legal_guardian', models.BooleanField()),
                ('status', models.PositiveIntegerField(choices=[(1, 'New'), (2, 'Confirmed'), (3, 'Down payment paid'), (4, 'Paid'), (5, 'Cancelled')])),
                ('submitted_at', models.DateTimeField(blank=True, help_text='The exact date and time signup was submitted.Date is generated automatically', null=True)),
                ('cancelled_for', models.TextField(blank=True, help_text='Write down a short explanation why was this signup cancelled', null=True)),
                ('batch_age_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='signups', to='fantasion_expeditions.batchagegroup')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='signups', to='fantasion_people.family')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='signups', to='fantasion_signups.participant')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('fantasion_eshop.orderitem',),
        ),
        migrations.CreateModel(
            name='SignupDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignupDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255)),
                ('title_cs', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True)),
                ('title_en', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True)),
                ('description', fantasion_generics.titles.DescriptionField(help_text='Object description')),
                ('description_cs', fantasion_generics.titles.DescriptionField(help_text='Object description', null=True)),
                ('description_en', fantasion_generics.titles.DescriptionField(help_text='Object description', null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('title',))),
                ('slug_cs', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=('title',))),
                ('slug_en', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=('title',))),
                ('required', models.BooleanField(default=False, help_text='Signup will be marked as incomplete until parent uploadsthis document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignupDocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('verified_on', models.DateField()),
                ('valid_until', models.DateField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='fantasion_signups.signupdocument')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='signup_document_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignupDocumentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveBigIntegerField(blank=True, null=True)),
                ('width', models.PositiveBigIntegerField(blank=True, null=True)),
                ('private_photo', models.ImageField(blank=True, height_field='height', max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Image file', width_field='width')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='fantasion_signups.signupdocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='signupdocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='fantasion_signups.signupdocumenttype'),
        ),
        migrations.AddField(
            model_name='signupdocument',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fantasion_signups.signup'),
        ),
    ]
