# Generated by Django 3.2.11 on 2022-01-16 18:15

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import fantasion_generics.media
import fantasion_generics.upload_path
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_people', '0002_auto_20220116_1915'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantasion_expeditions', '0002_auto_20220116_1915'),
        ('fantasion_signups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'Signup', 'verbose_name_plural': 'Signups'},
        ),
        migrations.AlterModelOptions(
            name='signupdocument',
            options={'verbose_name': 'Signup Document', 'verbose_name_plural': 'Signup Document'},
        ),
        migrations.AlterModelOptions(
            name='signupdocumenttype',
            options={'verbose_name': 'Signup Document Type', 'verbose_name_plural': 'Signup Document Type'},
        ),
        migrations.AlterModelOptions(
            name='signupdocumentverification',
            options={'verbose_name': 'Document Verification', 'verbose_name_plural': 'Document Verifications'},
        ),
        migrations.AlterField(
            model_name='participant',
            name='birthdate',
            field=models.DateField(verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='batch_age_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='signups', to='fantasion_expeditions.batchagegroup', verbose_name='Age Group'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='cancelled_for',
            field=models.TextField(blank=True, help_text='Write down a short explanation why was this signup cancelled', null=True, verbose_name='Cancelled for'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='signups', to='fantasion_people.family', verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='legal_guardian',
            field=models.BooleanField(verbose_name='Legal Guardian'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='signups', to='fantasion_signups.participant', verbose_name='Participant'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'New'), (2, 'Confirmed'), (3, 'Down payment paid'), (4, 'Paid'), (5, 'Cancelled')], verbose_name='Signup Status'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='The exact date and time signup was submitted.Date is generated automatically', null=True, verbose_name='Submitted at'),
        ),
        migrations.AlterField(
            model_name='signupdocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='fantasion_signups.signupdocumenttype', verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='signupdocument',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fantasion_signups.signup', verbose_name='Signup'),
        ),
        migrations.AlterField(
            model_name='signupdocumentmedia',
            name='height',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='signupdocumentmedia',
            name='parent',
            field=fantasion_generics.media.MediaParentField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='fantasion_signups.signupdocument', verbose_name='Parent object'),
        ),
        migrations.AlterField(
            model_name='signupdocumentmedia',
            name='private_photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Image file', width_field='width'),
        ),
        migrations.AlterField(
            model_name='signupdocumentmedia',
            name='width',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='signupdocumenttype',
            name='required',
            field=models.BooleanField(default=False, help_text='Signup will be marked as incomplete until parent uploadsthis document', verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='signupdocumentverification',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='fantasion_signups.signupdocument', verbose_name='Signup Document'),
        ),
        migrations.AlterField(
            model_name='signupdocumentverification',
            name='valid_until',
            field=models.DateField(help_text='This document will stay valid until it expires', verbose_name='Valid until'),
        ),
        migrations.AlterField(
            model_name='signupdocumentverification',
            name='verified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='signup_document_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Verified by'),
        ),
        migrations.AlterField(
            model_name='signupdocumentverification',
            name='verified_on',
            field=models.DateField(help_text='Date this document was verified', verbose_name='Verified on'),
        ),
    ]
