# Generated by Django 3.2.11 on 2022-02-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_signups', '0003_auto_20220131_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdocumenttype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='signupdocumenttype',
            name='slug_cs',
        ),
        migrations.RemoveField(
            model_name='signupdocumenttype',
            name='slug_en',
        ),
    ]
