# Generated by Django 3.2.12 on 2022-04-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_signups', '0004_auto_20220205_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.AddField(
            model_name='participant',
            name='first_name',
            field=models.CharField(default='', max_length=255, verbose_name='Given Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(default='', max_length=255, verbose_name='Family Name'),
            preserve_default=False,
        ),
    ]
