# Generated by Django 3.2.12 on 2022-04-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_signups', '0005_auto_20220402_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='batch_age_group',
            new_name='troop',
        ),
    ]
