# Generated by Django 3.2.12 on 2022-04-02 17:32

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_people', '0012_auto_20220205_1523'),
        ('fantasion_signups', '0007_auto_20220402_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantHobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participant_hobbies', to='fantasion_people.hobby')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_hobbies', to='fantasion_signups.participant')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
