# Generated by Django 3.2.12 on 2022-04-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_signups', '0009_participantdiet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantdiet',
            old_name='hobby',
            new_name='diet',
        ),
    ]
