# Generated by Django 3.2.12 on 2022-04-02 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_people', '0014_auto_20220402_1937'),
        ('fantasion_signups', '0010_rename_hobby_participantdiet_diet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantallergy',
            options={'verbose_name': 'Participant Allergy', 'verbose_name_plural': 'Participant Allergies'},
        ),
        migrations.AlterModelOptions(
            name='participantdiet',
            options={'verbose_name': 'Participant Diet', 'verbose_name_plural': 'Participant Diets'},
        ),
        migrations.AlterModelOptions(
            name='participanthobby',
            options={'verbose_name': 'Participant Hobby', 'verbose_name_plural': 'Participant Hobbies'},
        ),
        migrations.AlterField(
            model_name='participantallergy',
            name='allergy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participant_allergies', to='fantasion_people.allergy', verbose_name='Allergy'),
        ),
        migrations.AlterField(
            model_name='participantdiet',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participant_diets', to='fantasion_people.diet', verbose_name='Diet'),
        ),
        migrations.AlterField(
            model_name='participanthobby',
            name='hobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participant_hobbies', to='fantasion_people.hobby', verbose_name='Hobby'),
        ),
    ]
