# Generated by Django 3.2.12 on 2022-04-03 13:14

from django.db import migrations, models
import fantasion_signups.models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_signups', '0011_auto_20220403_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='legal_guardian',
            field=models.BooleanField(validators=[fantasion_signups.models.validate_legal_guardian], verbose_name='Legal Guardian'),
        ),
    ]
