# Generated by Django 3.2.12 on 2022-04-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_signups', '0012_alter_signup_legal_guardian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'New'), (2, 'Confirmed'), (3, 'Down payment paid'), (4, 'Paid'), (5, 'Cancelled')], default=1, verbose_name='Signup Status'),
        ),
    ]
