# Generated by Django 3.2.13 on 2022-04-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_signups', '0016_participant_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='no_allergies',
            field=models.BooleanField(default=False, verbose_name='Has no allergies'),
        ),
        migrations.AddField(
            model_name='participant',
            name='no_diets',
            field=models.BooleanField(default=False, verbose_name='Has no diets'),
        ),
        migrations.AddField(
            model_name='participant',
            name='no_hobbies',
            field=models.BooleanField(default=False, verbose_name='Has no hobbies'),
        ),
    ]
