# Generated by Django 3.2.13 on 2022-04-30 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_people', '0015_auto_20220501_0059'),
        ('fantasion_signups', '0017_auto_20220430_1739'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participantallergy',
            unique_together={('participant', 'allergy')},
        ),
        migrations.AlterUniqueTogether(
            name='participantdiet',
            unique_together={('participant', 'diet')},
        ),
        migrations.AlterUniqueTogether(
            name='participanthobby',
            unique_together={('participant', 'hobby')},
        ),
    ]
