import Head from 'next/head'
import React from 'react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fantasion</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <meta property="og:title" content="Fantasion" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://fantasion.cz" />
        <meta name="viewport" content="width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Fantasion</h1>
      </main>
    </div>
  )
}
