# Generated by Django 3.2.11 on 2022-01-16 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fantasion_eshop.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantasion_eshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='eshopproduct',
            options={'verbose_name': 'E-shop Product', 'verbose_name_plural': 'E-shop Products'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'E-shop Order', 'verbose_name_plural': 'E-shop Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'E-shop Order Item', 'verbose_name_plural': 'E-shop Order Items'},
        ),
        migrations.AlterModelOptions(
            name='pricelevel',
            options={'verbose_name': 'Price Level', 'verbose_name_plural': 'Price Levels'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name': 'E-shop Product Price', 'verbose_name_plural': 'E-shop Product Prices'},
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(help_text='Currency code respecting ISO 4217.', max_length=15, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='enabled',
            field=fantasion_eshop.models.EnabledField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, help_text='Exchange rate to base currency (CZK)', max_digits=9, verbose_name='Exchange rate'),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Order owner'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='fantasion_eshop.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='fantasion_eshop.order', verbose_name='E-shop Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='fantasion_eshop.productprice', verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='pricelevel',
            name='enabled',
            field=fantasion_eshop.models.EnabledField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='available_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Available since'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Available until'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prices', to='fantasion_eshop.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prices', to='fantasion_eshop.pricelevel', verbose_name='Price level'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='fantasion_eshop.eshopproduct', verbose_name='Product'),
        ),
    ]
