# Generated by Django 3.2.11 on 2022-01-31 22:29

import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields
import fantasion_eshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_eshop', '0004_auto_20220131_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(help_text='Type an unique code with combination of letters, numbers and symbols that are not too difficult to type', max_length=63, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Promotion Code')),
                ('enabled', fantasion_eshop.models.EnabledField(default=True, verbose_name='Enabled')),
                ('max_usages', models.PositiveIntegerField(help_text='This Promotion Code can be used only so many times, then it will be deactivated', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Usages')),
                ('valid_from', models.DateTimeField(blank=True, help_text='This Promotion Code will be invalid until this date and time', null=True, verbose_name='Valid from')),
                ('valid_until', models.DateTimeField(blank=True, help_text='This Promotion Code will be invalid after this date and time', null=True, verbose_name='Valid until')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
