# Generated by Django 3.2.11 on 2022-01-31 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_eshop', '0005_promotioncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotioncode',
            name='max_usages',
            field=models.PositiveIntegerField(default=10, help_text='This Promotion Code can be used only so many times, then it will be deactivated', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Usages'),
        ),
    ]
