# Generated by Django 3.2.11 on 2022-02-01 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_eshop', '0006_alter_promotioncode_max_usages'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncode',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.01, help_text='This percentage will be cut of the total order price.', max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0.01)], verbose_name='Discount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotioncode',
            name='max_discount',
            field=models.PositiveIntegerField(blank=True, help_text='The system will cap the absolute discount. Use base currency (CZK)', null=True, verbose_name='Maximum discount'),
        ),
    ]
