# Generated by Django 3.2.11 on 2022-02-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_eshop', '0007_auto_20220201_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotioncode',
            options={'verbose_name': 'Promotion Code', 'verbose_name_plural': 'Promotion Codes'},
        ),
    ]
