# Generated by Django 3.2.11 on 2022-02-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_eshop', '0008_alter_promotioncode_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelevel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='pricelevel',
            name='slug_cs',
        ),
        migrations.RemoveField(
            model_name='pricelevel',
            name='slug_en',
        ),
    ]
