# Generated by Django 3.2.12 on 2022-04-02 10:48

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_eshop', '0009_auto_20220205_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='CZK', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna'), ('EUR', 'Euro')], default='CZK', editable=False, max_length=3),
        ),
    ]
