# Generated by Django 3.2.12 on 2022-04-02 11:04

from django.db import migrations
from djmoney.money import Money
import djmoney.models.fields
import fantasion_generics.money


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_eshop', '0010_auto_20220402_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='currency',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna')], default='CZK', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=fantasion_generics.money.MoneyField(decimal_places=2, default_currency='CZK', max_digits=14, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=fantasion_generics.money.MoneyField(decimal_places=2, default=Money(0, 'CZK'), default_currency='CZK', max_digits=14, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('product', 'price_level')},
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
