# Generated by Django 3.2.12 on 2022-04-02 11:47

from django.db import migrations
import djmoney.models.fields
import fantasion_generics.money


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_eshop', '0011_auto_20220402_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncode',
            name='max_discount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna')], default='CZK', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=fantasion_generics.money.MoneyField(decimal_places=2, default_currency='CZK', max_digits=14, verbose_name='Real Price'),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='max_discount',
            field=fantasion_generics.money.MoneyField(blank=True, decimal_places=2, default_currency='CZK', help_text='The system will cap the absolute discount.', max_digits=14, null=True, verbose_name='Maximum discount'),
        ),
    ]
