# Generated by Django 3.2.12 on 2022-04-02 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantasion_eshop', '0012_auto_20220402_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='fantasion.user', verbose_name='Order owner'),
            preserve_default=False,
        ),
    ]
