# Generated by Django 3.2.12 on 2022-04-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_eshop', '0014_auto_20220402_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpromotioncode',
            options={'verbose_name': 'Order Promotion Code', 'verbose_name_plural': 'Order Promotion Codes'},
        ),
    ]
