# Generated by Django 3.2.12 on 2022-04-02 13:43

from django.db import migrations
from djmoney.money import Money
import djmoney.models.fields
import fantasion_generics.money


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_eshop', '0016_orderitem_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=fantasion_generics.money.MoneyField(decimal_places=2, default=Money(0, 'CZK'), default_currency='CZK', max_digits=14, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna')], default='CZK', editable=False, max_length=3),
        ),
    ]
