# Generated by Django 3.2.12 on 2022-04-02 16:22

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import fantasion_generics.money


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_eshop', '0017_auto_20220402_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit',
            field=fantasion_generics.money.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='CZK', help_text='Calculated based on Order Items configuration', max_digits=14, verbose_name='Deposit'),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna')], default='CZK', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='use_deposit_payment',
            field=models.BooleanField(default=False, help_text='System will split the payment into deposit and surcharge based on Order Items configuration', verbose_name='Use Deposit Payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=fantasion_generics.money.MoneyField(decimal_places=2, default_currency='CZK', help_text='This is the total price that will be charged to the user', max_digits=14, verbose_name='Price'),
        ),
    ]
