# Generated by Django 3.2.12 on 2022-04-02 17:25

from decimal import Decimal
from django.db import migrations
import fantasion_generics.money


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_eshop', '0018_auto_20220402_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deposit',
            field=fantasion_generics.money.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='CZK', max_digits=14, verbose_name='Deposit'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=fantasion_generics.money.MoneyField(decimal_places=2, default_currency='CZK', max_digits=14, verbose_name='Total Price'),
        ),
    ]
