# Generated by Django 3.2.12 on 2022-04-03 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_banking', '0005_debt_debt_type'),
        ('fantasion_eshop', '0019_auto_20220402_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasion_banking.promise', verbose_name='Payment Promise'),
        ),
    ]
