# Generated by Django 3.2.12 on 2022-04-09 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion', '0009_useraddress'),
        ('fantasion_locations', '0003_auto_20220123_0335'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantasion_eshop', '0023_order_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_invoice_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fantasion.useraddress'),
        ),
        migrations.CreateModel(
            name='OrderInvoiceAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('city', models.CharField(blank=True, max_length=127, null=True, verbose_name='City')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street')),
                ('street_number', models.CharField(blank=True, max_length=63, null=True, verbose_name='Street number')),
                ('postal_code', models.CharField(blank=True, max_length=63, null=True, verbose_name='Postal code')),
                ('title', models.CharField(help_text='Human readable identifier that will help user select this address, like "Home"', max_length=32, verbose_name='Title')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_invoice_addresses', to='fantasion_locations.country', verbose_name='Country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
                'abstract': False,
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fantasion_eshop.orderinvoiceaddress'),
        ),
    ]
