# Generated by Django 3.2.12 on 2022-04-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_eshop', '0024_auto_20220409_1608'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderinvoiceaddress',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderinvoiceaddress',
            name='title',
        ),
    ]
