# Generated by Django 3.2.12 on 2022-04-11 23:42

from django.db import migrations
import fantasion_generics.models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_eshop', '0026_order_request_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='eshopproduct',
            name='price_includes',
            field=fantasion_generics.models.MarkdownField(blank=True, help_text='Desription of services included in price', null=True, verbose_name='Price includes'),
        ),
    ]
