# Generated by Django 3.2.13 on 2022-05-01 19:03

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_eshop', '0027_eshopproduct_price_includes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='invoices/%Y/%m'),
        ),
    ]
