# Generated by Django 4.1.5 on 2023-01-09 13:07

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_eshop', '0027_eshopproduct_price_includes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deposit_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Kč')], default='CZK', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Kč')], default='CZK', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Kč')], default='CZK', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Kč')], default='CZK', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='max_discount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Kč')], default='CZK', editable=False, max_length=3, null=True),
        ),
    ]
