# Generated by Django 4.1.10 on 2023-07-30 03:51

from decimal import Decimal
from django.db import migrations
import fantasion_generics.money


class Migration(migrations.Migration):
    dependencies = [
        ("fantasion_eshop", "0028_alter_order_deposit_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="price",
            field=fantasion_generics.money.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="CZK",
                max_digits=14,
                verbose_name="Total Price",
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="price",
            field=fantasion_generics.money.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="CZK",
                max_digits=14,
                verbose_name="Price",
            ),
        ),
    ]
