# Generated by Django 4.1.10 on 2024-12-29 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_eshop', '0029_alter_order_price_alter_productprice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotioncode',
            name='code',
            field=models.CharField(help_text='Type an unique code with combination of letters, numbers and symbols that are not too difficult to type', max_length=63, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Promotion Code'),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='discount',
            field=models.DecimalField(decimal_places=3, help_text='This percentage will be cut of the total order price.', max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0.001)], verbose_name='Discount'),
        ),
    ]
