# Generated by Django 3.2.10 on 2021-12-30 23:09

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import fantasion_generics.titles
import fantasion_generics.upload_path
import fantasion_generics.videos


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fantasion_people', '0001_initial'),
        ('fantasion_eshop', '__first__'),
        ('fantasion_locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255)),
                ('title_cs', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True)),
                ('title_en', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True)),
                ('age_min', models.PositiveIntegerField(verbose_name='Minimal age')),
                ('age_max', models.PositiveIntegerField(verbose_name='Maximal age')),
            ],
            options={
                'ordering': ['age_min', 'age_max', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255)),
                ('title_cs', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True)),
                ('title_en', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True)),
                ('description', fantasion_generics.titles.DescriptionField(help_text='Object description')),
                ('description_cs', fantasion_generics.titles.DescriptionField(help_text='Object description', null=True)),
                ('description_en', fantasion_generics.titles.DescriptionField(help_text='Object description', null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('title',))),
                ('slug_cs', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=('title',))),
                ('slug_en', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=('title',))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpeditionProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255)),
                ('title_cs', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True)),
                ('title_en', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True)),
                ('description', fantasion_generics.titles.DescriptionField(help_text='Object description')),
                ('description_cs', fantasion_generics.titles.DescriptionField(help_text='Object description', null=True)),
                ('description_en', fantasion_generics.titles.DescriptionField(help_text='Object description', null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('title',))),
                ('slug_cs', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=('title',))),
                ('slug_en', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=('title',))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeisureCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255)),
                ('title_cs', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True)),
                ('title_en', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True)),
                ('description', fantasion_generics.titles.DescriptionField(help_text='Object description')),
                ('description_cs', fantasion_generics.titles.DescriptionField(help_text='Object description', null=True)),
                ('description_en', fantasion_generics.titles.DescriptionField(help_text='Object description', null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('title',))),
                ('slug_cs', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=('title',))),
                ('slug_en', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=('title',))),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('location', models.ForeignKey(help_text='This location will be posted on the map and used for navigation.', on_delete=django.db.models.deletion.RESTRICT, related_name='leisure_centres', to='fantasion_locations.location')),
                ('mailing_address', models.ForeignKey(blank=True, help_text='This location will be used as a postal address,instruct people to mail here.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='leisure_centre_mailing_addresses', to='fantasion_locations.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255)),
                ('title_cs', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True)),
                ('title_en', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True)),
                ('description', fantasion_generics.titles.DescriptionField(help_text='Object description')),
                ('description_cs', fantasion_generics.titles.DescriptionField(help_text='Object description', null=True)),
                ('description_en', fantasion_generics.titles.DescriptionField(help_text='Object description', null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('title',))),
                ('slug_cs', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=('title',))),
                ('slug_en', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=('title',))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffRoleMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('height', models.PositiveBigIntegerField(blank=True, null=True)),
                ('width', models.PositiveBigIntegerField(blank=True, null=True)),
                ('local_photo', models.ImageField(blank=True, height_field='height', max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Image file', width_field='width')),
                ('local_video', fantasion_generics.videos.VideoField(blank=True, duration_field='duration', height_field='height', max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Video file', width_field='width')),
                ('duration', models.PositiveBigIntegerField(blank=True, null=True)),
                ('title', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('description', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='fantasion_expeditions.staffrole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeisureCentreMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('height', models.PositiveBigIntegerField(blank=True, null=True)),
                ('width', models.PositiveBigIntegerField(blank=True, null=True)),
                ('local_photo', models.ImageField(blank=True, height_field='height', max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Image file', width_field='width')),
                ('local_video', fantasion_generics.videos.VideoField(blank=True, duration_field='duration', height_field='height', max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Video file', width_field='width')),
                ('duration', models.PositiveBigIntegerField(blank=True, null=True)),
                ('title', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('title_cs', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('title_en', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('description', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
                ('description_cs', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
                ('description_en', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='fantasion_expeditions.leisurecentre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpeditionProgramMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('height', models.PositiveBigIntegerField(blank=True, null=True)),
                ('width', models.PositiveBigIntegerField(blank=True, null=True)),
                ('local_photo', models.ImageField(blank=True, height_field='height', max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Image file', width_field='width')),
                ('local_video', fantasion_generics.videos.VideoField(blank=True, duration_field='duration', height_field='height', max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Video file', width_field='width')),
                ('duration', models.PositiveBigIntegerField(blank=True, null=True)),
                ('title', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('title_cs', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('title_en', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('description', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
                ('description_cs', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
                ('description_en', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='fantasion_expeditions.expeditionprogram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpeditionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('height', models.PositiveBigIntegerField(blank=True, null=True)),
                ('width', models.PositiveBigIntegerField(blank=True, null=True)),
                ('local_photo', models.ImageField(blank=True, height_field='height', max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Image file', width_field='width')),
                ('local_video', fantasion_generics.videos.VideoField(blank=True, duration_field='duration', height_field='height', max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Video file', width_field='width')),
                ('duration', models.PositiveBigIntegerField(blank=True, null=True)),
                ('title', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('title_cs', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('title_en', fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True)),
                ('description', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
                ('description_cs', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
                ('description_en', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='fantasion_expeditions.expedition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpeditionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='fantasion_expeditions.expedition', verbose_name='Expedition')),
                ('leisure_centre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='expedition_batches', to='fantasion_expeditions.leisurecentre', verbose_name='Leisure Centre')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatchStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='fantasion_expeditions.expeditionbatch')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='expedition_roles', to='fantasion_people.profile')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='staff', to='fantasion_expeditions.staffrole')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatchAgeGroup',
            fields=[
                ('eshopproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fantasion_eshop.eshopproduct')),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='age_group_batches', to='fantasion_expeditions.agegroup')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_groups', to='fantasion_expeditions.expeditionbatch')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='age_group_batches', to='fantasion_expeditions.expeditionprogram')),
            ],
            options={
                'unique_together': {('batch', 'age_group', 'starts_at')},
            },
            bases=('fantasion_eshop.eshopproduct',),
        ),
    ]
