# Generated by Django 3.2.11 on 2022-01-18 18:13

from django.db import migrations
import fantasion_generics.titles


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_expeditions', '0003_expeditionbatch_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrolemedia',
            name='description_cs',
            field=fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='staffrolemedia',
            name='description_en',
            field=fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Object description', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='staffrolemedia',
            name='title_cs',
            field=fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='staffrolemedia',
            name='title_en',
            field=fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
