# Generated by Django 3.2.11 on 2022-01-31 23:52

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import fantasion_generics.media
import fantasion_generics.models
import fantasion_generics.titles
import fantasion_generics.upload_path
import fantasion_generics.videos
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_expeditions', '0008_auto_20220131_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpeditionTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, verbose_name='Title')),
                ('title_cs', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True, verbose_name='Title')),
                ('title_en', fantasion_generics.titles.TitleField(help_text='Object name', max_length=255, null=True, verbose_name='Title')),
                ('description', fantasion_generics.titles.DescriptionField(help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', verbose_name='Short Description')),
                ('description_cs', fantasion_generics.titles.DescriptionField(help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description')),
                ('description_en', fantasion_generics.titles.DescriptionField(help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('title',))),
                ('slug_cs', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=('title',))),
                ('slug_en', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=('title',))),
                ('detailed_description', fantasion_generics.models.DetailedDescriptionField(blank=True, help_text='Detailed verbose description formatted in Markdown. Thereis no text limit.', null=True, verbose_name='Detailed Description')),
                ('detailed_description_cs', fantasion_generics.models.DetailedDescriptionField(blank=True, help_text='Detailed verbose description formatted in Markdown. Thereis no text limit.', null=True, verbose_name='Detailed Description')),
                ('detailed_description_en', fantasion_generics.models.DetailedDescriptionField(blank=True, help_text='Detailed verbose description formatted in Markdown. Thereis no text limit.', null=True, verbose_name='Detailed Description')),
            ],
            options={
                'verbose_name': 'Expedition Theme',
                'verbose_name_plural': 'Expedition Themes',
            },
        ),
        migrations.CreateModel(
            name='ExpeditionThemeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Height')),
                ('width', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Width')),
                ('local_photo', versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Image file', width_field='width')),
                ('local_video', fantasion_generics.videos.VideoField(blank=True, duration_field='duration', height_field='height', max_length=255, null=True, upload_to=fantasion_generics.upload_path.get_upload_path, verbose_name='Video file', width_field='width')),
                ('duration', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description')),
                ('description_cs', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description')),
                ('description_en', fantasion_generics.titles.FacultativeDescriptionField(blank=True, help_text='Describe this in a couple of sentences. Use Markdown if necessary, but keeping this a plain text will yield better results', null=True, verbose_name='Short Description')),
                ('parent', fantasion_generics.media.MediaParentField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='fantasion_expeditions.expeditiontheme', verbose_name='Parent object')),
            ],
            options={
                'verbose_name': 'Media Object',
                'verbose_name_plural': 'Media Objects',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='expedition',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fantasion_expeditions.expeditiontheme', verbose_name='Expedition Theme'),
        ),
    ]
