# Generated by Django 3.2.11 on 2022-02-01 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_expeditions', '0010_alter_batchagegroup_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='expeditions', to='fantasion_expeditions.expeditiontheme', verbose_name='Expedition Theme'),
        ),
    ]
