# Generated by Django 3.2.11 on 2022-02-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_signups', '0003_auto_20220131_2229'),
        ('fantasion_eshop', '0008_alter_promotioncode_options'),
        ('fantasion_expeditions', '0012_auto_20220201_1852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BatchAgeGroup',
            new_name='Troop',
        ),
    ]
