# Generated by Django 3.2.11 on 2022-02-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_expeditions', '0013_rename_batchagegroup_troop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='troop',
            options={'verbose_name': 'Troop', 'verbose_name_plural': 'Troops'},
        ),
    ]
