# Generated by Django 3.2.11 on 2022-02-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_expeditions', '0015_auto_20220202_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='slug_cs',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='expeditionprogram',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='expeditionprogram',
            name='slug_cs',
        ),
        migrations.RemoveField(
            model_name='expeditionprogram',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='expeditiontheme',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='expeditiontheme',
            name='slug_cs',
        ),
        migrations.RemoveField(
            model_name='expeditiontheme',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='leisurecentre',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='leisurecentre',
            name='slug_cs',
        ),
        migrations.RemoveField(
            model_name='leisurecentre',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='staffrole',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='staffrole',
            name='slug_cs',
        ),
        migrations.RemoveField(
            model_name='staffrole',
            name='slug_en',
        ),
    ]
