# Generated by Django 3.2.13 on 2022-07-23 21:23

from django.db import migrations
import fantasion_generics.titles


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_expeditions', '0017_transport_transportvehicle_transportvehiclemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportvehicle',
            name='title',
            field=fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
