# Generated by Django 3.2.13 on 2022-07-23 21:25

from django.db import migrations
import fantasion_generics.models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_expeditions', '0018_transportvehicle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='description',
            field=fantasion_generics.models.DetailedDescriptionField(blank=True, help_text='Detailed verbose description formatted in Markdown. Thereis no text limit.', null=True, verbose_name='Detailed Description'),
        ),
        migrations.AlterField(
            model_name='transportvehicle',
            name='title',
            field=fantasion_generics.models.DetailedDescriptionField(blank=True, help_text='Detailed verbose description formatted in Markdown. Thereis no text limit.', null=True, verbose_name='Detailed Description'),
        ),
    ]
