# Generated by Django 3.2.13 on 2022-07-23 21:39

from django.db import migrations
import fantasion_generics.models
import fantasion_generics.titles


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_expeditions', '0020_auto_20220723_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportvehicle',
            name='description',
            field=fantasion_generics.models.DetailedDescriptionField(blank=True, help_text='Detailed verbose description formatted in Markdown. Thereis no text limit.', null=True, verbose_name='Detailed Description'),
        ),
        migrations.AlterField(
            model_name='transportvehicle',
            name='description_cs',
            field=fantasion_generics.models.DetailedDescriptionField(blank=True, help_text='Detailed verbose description formatted in Markdown. Thereis no text limit.', null=True, verbose_name='Detailed Description'),
        ),
        migrations.AlterField(
            model_name='transportvehicle',
            name='description_en',
            field=fantasion_generics.models.DetailedDescriptionField(blank=True, help_text='Detailed verbose description formatted in Markdown. Thereis no text limit.', null=True, verbose_name='Detailed Description'),
        ),
        migrations.AlterField(
            model_name='transportvehicle',
            name='title',
            field=fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='transportvehicle',
            name='title_cs',
            field=fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='transportvehicle',
            name='title_en',
            field=fantasion_generics.titles.FacultativeTitleField(blank=True, help_text='Object name', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
