# Generated by Django 3.2.13 on 2022-07-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_expeditions', '0021_auto_20220723_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='arrived',
            field=models.BooleanField(default=False, help_text='The transport has reached the destination', verbose_name='Arrived'),
        ),
        migrations.AddField(
            model_name='transport',
            name='boarding',
            field=models.BooleanField(default=False, help_text='The transport is boarding at the moment', verbose_name='Boarding'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='gps_tracking_url',
            field=models.URLField(blank=True, help_text='Tracking URL will be published until the transport arrives tothe destination', null=True, verbose_name='GPS Tracking URL'),
        ),
    ]
