# Generated by Django 3.2.13 on 2022-07-23 22:02

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_expeditions', '0022_auto_20220723_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroopTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='troop_transports', to='fantasion_expeditions.transport', verbose_name='Transport')),
                ('troop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troop_transports', to='fantasion_expeditions.troop', verbose_name='Troop')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
