# Generated by Django 3.2.13 on 2022-07-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_expeditions', '0023_trooptransport'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='departed',
            field=models.BooleanField(default=False, help_text='The transport has departed', verbose_name='Departed'),
        ),
    ]
