# Generated by Django 3.2.13 on 2022-07-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_expeditions', '0026_auto_20220724_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='trooptransport',
            name='direction',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Transport There'), (2, 'Transport Back')], null=True),
        ),
    ]
