# Generated by Django 4.1.5 on 2023-01-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasion_expeditions', '0029_auto_20220728_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expeditionlogarticle',
            options={'ordering': ('-date', '-created'), 'verbose_name': 'Expedition Log Article', 'verbose_name_plural': 'Expedition Log Articles'},
        ),
    ]
