# Generated by Django 4.1.5 on 2023-01-21 14:51

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields
import fantasion_generics.models
import fantasion_generics.visibility


class Migration(migrations.Migration):

    dependencies = [
        ("fantasion_expeditions", "0030_alter_expeditionlogarticle_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expedition",
            name="public",
        ),
        migrations.RemoveField(
            model_name="expeditionbatch",
            name="public",
        ),
        migrations.RemoveField(
            model_name="expeditionlogarticle",
            name="public",
        ),
        migrations.RemoveField(
            model_name="transport",
            name="public",
        ),
        migrations.RemoveField(
            model_name="transportvehicle",
            name="public",
        ),
        migrations.AddField(
            model_name="expedition",
            name="visibility",
            field=fantasion_generics.visibility.VisibilityField(
                choices=[(1, "🌐 Public"), (2, "🔒 Private"), (3, "🚫 Hidden")],
                default=1,
                help_text="Public objects will be visible on the website",
                verbose_name="Visibility",
            ),
        ),
        migrations.AddField(
            model_name="expeditionbatch",
            name="visibility",
            field=fantasion_generics.visibility.VisibilityField(
                choices=[(1, "🌐 Public"), (2, "🔒 Private"), (3, "🚫 Hidden")],
                default=1,
                help_text="Public objects will be visible on the website",
                verbose_name="Visibility",
            ),
        ),
        migrations.AddField(
            model_name="expeditionlogarticle",
            name="description",
            field=fantasion_generics.models.DetailedDescriptionField(
                blank=True,
                help_text="Detailed verbose description formatted in Markdown. Thereis no text limit.",
                null=True,
                verbose_name="Detailed Description",
            ),
        ),
        migrations.AddField(
            model_name="expeditionlogarticle",
            name="description_cs",
            field=fantasion_generics.models.DetailedDescriptionField(
                blank=True,
                help_text="Detailed verbose description formatted in Markdown. Thereis no text limit.",
                null=True,
                verbose_name="Detailed Description",
            ),
        ),
        migrations.AddField(
            model_name="expeditionlogarticle",
            name="description_en",
            field=fantasion_generics.models.DetailedDescriptionField(
                blank=True,
                help_text="Detailed verbose description formatted in Markdown. Thereis no text limit.",
                null=True,
                verbose_name="Detailed Description",
            ),
        ),
        migrations.AddField(
            model_name="expeditionlogarticle",
            name="visibility",
            field=fantasion_generics.visibility.VisibilityField(
                choices=[(1, "🌐 Public"), (2, "🔒 Private"), (3, "🚫 Hidden")],
                default=1,
                help_text="Public objects will be visible on the website",
                verbose_name="Visibility",
            ),
        ),
        migrations.AddField(
            model_name="expeditionprogram",
            name="visibility",
            field=fantasion_generics.visibility.VisibilityField(
                choices=[(1, "🌐 Public"), (2, "🔒 Private"), (3, "🚫 Hidden")],
                default=1,
                help_text="Public objects will be visible on the website",
                verbose_name="Visibility",
            ),
        ),
        migrations.AddField(
            model_name="expeditiontheme",
            name="visibility",
            field=fantasion_generics.visibility.VisibilityField(
                choices=[(1, "🌐 Public"), (2, "🔒 Private"), (3, "🚫 Hidden")],
                default=1,
                help_text="Public objects will be visible on the website",
                verbose_name="Visibility",
            ),
        ),
        migrations.AddField(
            model_name="leisurecentre",
            name="visibility",
            field=fantasion_generics.visibility.VisibilityField(
                choices=[(1, "🌐 Public"), (2, "🔒 Private"), (3, "🚫 Hidden")],
                default=1,
                help_text="Public objects will be visible on the website",
                verbose_name="Visibility",
            ),
        ),
        migrations.AddField(
            model_name="transport",
            name="visibility",
            field=fantasion_generics.visibility.VisibilityField(
                choices=[(1, "🌐 Public"), (2, "🔒 Private"), (3, "🚫 Hidden")],
                default=1,
                help_text="Public objects will be visible on the website",
                verbose_name="Visibility",
            ),
        ),
        migrations.AddField(
            model_name="transportvehicle",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transportvehicle",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="transportvehicle",
            name="visibility",
            field=fantasion_generics.visibility.VisibilityField(
                choices=[(1, "🌐 Public"), (2, "🔒 Private"), (3, "🚫 Hidden")],
                default=1,
                help_text="Public objects will be visible on the website",
                verbose_name="Visibility",
            ),
        ),
        migrations.AlterField(
            model_name="expedition",
            name="description",
            field=fantasion_generics.models.DetailedDescriptionField(
                blank=True,
                help_text="Detailed verbose description formatted in Markdown. Thereis no text limit.",
                null=True,
                verbose_name="Detailed Description",
            ),
        ),
        migrations.AlterField(
            model_name="expedition",
            name="description_cs",
            field=fantasion_generics.models.DetailedDescriptionField(
                blank=True,
                help_text="Detailed verbose description formatted in Markdown. Thereis no text limit.",
                null=True,
                verbose_name="Detailed Description",
            ),
        ),
        migrations.AlterField(
            model_name="expedition",
            name="description_en",
            field=fantasion_generics.models.DetailedDescriptionField(
                blank=True,
                help_text="Detailed verbose description formatted in Markdown. Thereis no text limit.",
                null=True,
                verbose_name="Detailed Description",
            ),
        ),
        migrations.AlterField(
            model_name="expeditionprogram",
            name="description",
            field=fantasion_generics.models.DetailedDescriptionField(
                blank=True,
                help_text="Detailed verbose description formatted in Markdown. Thereis no text limit.",
                null=True,
                verbose_name="Detailed Description",
            ),
        ),
        migrations.AlterField(
            model_name="expeditionprogram",
            name="description_cs",
            field=fantasion_generics.models.DetailedDescriptionField(
                blank=True,
                help_text="Detailed verbose description formatted in Markdown. Thereis no text limit.",
                null=True,
                verbose_name="Detailed Description",
            ),
        ),
        migrations.AlterField(
            model_name="expeditionprogram",
            name="description_en",
            field=fantasion_generics.models.DetailedDescriptionField(
                blank=True,
                help_text="Detailed verbose description formatted in Markdown. Thereis no text limit.",
                null=True,
                verbose_name="Detailed Description",
            ),
        ),
        migrations.AlterField(
            model_name="expeditiontheme",
            name="description",
            field=fantasion_generics.models.DetailedDescriptionField(
                blank=True,
                help_text="Detailed verbose description formatted in Markdown. Thereis no text limit.",
                null=True,
                verbose_name="Detailed Description",
            ),
        ),
        migrations.AlterField(
            model_name="expeditiontheme",
            name="description_cs",
            field=fantasion_generics.models.DetailedDescriptionField(
                blank=True,
                help_text="Detailed verbose description formatted in Markdown. Thereis no text limit.",
                null=True,
                verbose_name="Detailed Description",
            ),
        ),
        migrations.AlterField(
            model_name="expeditiontheme",
            name="description_en",
            field=fantasion_generics.models.DetailedDescriptionField(
                blank=True,
                help_text="Detailed verbose description formatted in Markdown. Thereis no text limit.",
                null=True,
                verbose_name="Detailed Description",
            ),
        ),
        migrations.AlterField(
            model_name="leisurecentre",
            name="description",
            field=fantasion_generics.models.DetailedDescriptionField(
                blank=True,
                help_text="Detailed verbose description formatted in Markdown. Thereis no text limit.",
                null=True,
                verbose_name="Detailed Description",
            ),
        ),
        migrations.AlterField(
            model_name="leisurecentre",
            name="description_cs",
            field=fantasion_generics.models.DetailedDescriptionField(
                blank=True,
                help_text="Detailed verbose description formatted in Markdown. Thereis no text limit.",
                null=True,
                verbose_name="Detailed Description",
            ),
        ),
        migrations.AlterField(
            model_name="leisurecentre",
            name="description_en",
            field=fantasion_generics.models.DetailedDescriptionField(
                blank=True,
                help_text="Detailed verbose description formatted in Markdown. Thereis no text limit.",
                null=True,
                verbose_name="Detailed Description",
            ),
        ),
    ]
